version: "2"

services:

  upload:
    build: .
    ports:
    - "18180:8180"
    volumes:
    - ngx:/etc/nginx/www

  php:
    image: php:5.6-fpm
    volumes:
    - ngx:/etc/nginx/www

volumes:
  ngx: